using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace EFMago.Models
{
    public partial class MaManufacturingParameters
    {
        public int ManufacturingParametersId { get; set; }
        public int? JobTicketType { get; set; }
        public short? PlanningHorizon { get; set; }
        public short? Mrphorizon { get; set; }
        public string DefaultStorage { get; set; }
        public string PickingStorage { get; set; }
        public string InHouseRmreservInvRsn { get; set; }
        public string OutsrcRmreservInvRsn { get; set; }
        public string InHouseRmpickingInvRsn { get; set; }
        public string OutsrcRmpickingInvRsn { get; set; }
        public string InHouseFpreceiptInvRsn { get; set; }
        public string OutsrcFpreceiptInvRsn { get; set; }
        public string InHouseRmissueInvRsn { get; set; }
        public string OutsrcRmissueInvRsn { get; set; }
        public string InHouseToOutsrcInvRsn { get; set; }
        public string OutsrcToInHouseInvRsn { get; set; }
        public string InHouseScrapInvRsn { get; set; }
        public string OutsrcScrapInvRsn { get; set; }
        public string OutsrcToOutsrcInvRsn { get; set; }
        public string SubcntDnrsn { get; set; }
        public string SubcntOrdRsn { get; set; }
        public string SimplifiedInventoryEntries { get; set; }
        public string PreparePickingList { get; set; }
        public string BoLmandatory { get; set; }
        public string StepsCheck { get; set; }
        public string SupplierDocOptionalNote { get; set; }
        public string PreparePickingLists { get; set; }
        public string PickAlsoMissingMocomponents { get; set; }
        public string PickMocomponents { get; set; }
        public string PrepareSubcntOrd { get; set; }
        public string DinstinctFixedCost { get; set; }
        public string PrepareSubcntDn { get; set; }
        public string PrepareShopFloorPapers { get; set; }
        public short? ModisplayForType { get; set; }
        public int? ModisplayForStatus { get; set; }
        public string SubcntDnbeginningText { get; set; }
        public string SubcntDnendingText { get; set; }
        public string SearchInSupplierStorage { get; set; }
        public string SearchInDefaultStorage { get; set; }
        public string OverIssue { get; set; }
        public string ConfirmChildMo { get; set; }
        public string AskConfirmChildMo { get; set; }
        public string UseMochildAvailability { get; set; }
        public string ValueOnlyPartialSfreceipt { get; set; }
        public string PickProductionLotFromStorage { get; set; }
        public string SearchOnlyInSubcntStorage { get; set; }
        public string PickingListCheck { get; set; }
        public string PickComponentsCheck { get; set; }
        public string CopyOnPreviousSteps { get; set; }
        public string SubcntDnandOrd { get; set; }
        public string SubcntBoLrsn { get; set; }
        public string ReturnedMaterialRsn { get; set; }
        public string RecalculateActualCosts { get; set; }
        public string GroupMocomponents { get; set; }
        public string UseStepCosts { get; set; }
        public string SubcontractorStorage { get; set; }
        public string LotOverbook { get; set; }
        public string LastStepMocomponentsCheck { get; set; }
        public string InHouseSrloadInvRsn { get; set; }
        public string OutsrcSrloadInvRsn { get; set; }
        public string UseOriginalComponent { get; set; }
        public string OldModeStepTimeCalc { get; set; }
        public string SkipNotWorkingDays { get; set; }
        public string UseOrderReleaseDays { get; set; }
        public string UseAnticipationDays { get; set; }
        public string UseCorrectionManagement { get; set; }
        public string PickingStorageSemifinished { get; set; }
        public string TotalTime { get; set; }
        public string ProcessingQtyTime { get; set; }
        public string DefaultSfstorage { get; set; }
        public string DefaultExtStorage { get; set; }
        public string DefaultExtSfstorage { get; set; }
        public string SeparateOrderForMo { get; set; }
        public string CalculateCostSecondRate { get; set; }
        public string CalculateCostScrap { get; set; }
        public string DefaultScrapStorage { get; set; }
        public string DefaultSecondRateStorage { get; set; }
        public string DefaultExtScrapStorage { get; set; }
        public string DefaultExtSecondRateStorage { get; set; }
        public string DenyInteractMatReqPicking { get; set; }
        public string DenyAutomaticMatReqPicking { get; set; }
        public string UseRtgStepPicking { get; set; }
        public string CalculateMocostUsingMochild { get; set; }
        public string AskConfirmPickingList { get; set; }
        public string ConfirmRoutingStep { get; set; }
        public string AskConfirmRoutingStep { get; set; }
        public string ConfirmClosureRoutingStep { get; set; }
        public string AskConfirmClosureRoutingStep { get; set; }
        public string AskConfirmMajorPicking { get; set; }
        public string UnderIssue { get; set; }
        public string AskConfirmMinorPicking { get; set; }
        public string NetFirstLevelOnJobPolicy { get; set; }
        public string NetOtherLevelsOnJobPolicy { get; set; }
        public string NetFirstLevelOnLotPolicy { get; set; }
        public string NetOtherLevelsOnLotPolicy { get; set; }
        public string NetFirstLevelOnDayReqPolicy { get; set; }
        public string NetOtherLevelsOnDayReqPolicy { get; set; }
        public string NetByItemMaster { get; set; }
        public string NetByMo { get; set; }
        public string NetByMoEmptyJob { get; set; }
        public string NetByPurchOrd { get; set; }
        public short? Horizon { get; set; }
        public int? HrzType { get; set; }
        public int? ForecastRequireDay { get; set; }
        public int? ForecastRequireWeekDay { get; set; }
        public string IntegratePl { get; set; }
        public string AskIntegratePl { get; set; }
        public string ReturnMaterial { get; set; }
        public string AskReturnMaterial { get; set; }
        public string CopyOnPrevStepsMoconfirmed { get; set; }
        public string OutsourceProcessingCostCheck { get; set; }
        public string AskConfirmFirstStepOnly { get; set; }
        public string IssueInvRsn { get; set; }
        public string ClearingInvRsn { get; set; }
        public string UseStandardCostForSf { get; set; }
        public string InHouseStdSfreservInvRsn { get; set; }
        public string OutsrcStdSfreservInvRsn { get; set; }
        public string DrawingAsItemAlias { get; set; }
        public string UseDnstoragesAndLots { get; set; }
        public string DifferentSubcntrStorages { get; set; }
        public string StdLoadsAdjustmentInvRsn { get; set; }
        public string Calendar { get; set; }
        public string AssignLotStorageOnPicking { get; set; }
        public string CheckLotOnMoconfPicking { get; set; }
        public string BlockLotOnMoconfPicking { get; set; }
        public string SetDnstorages { get; set; }
        public string SetProcessingQtyOnNextStep { get; set; }
        public int? LotGenerationMoment { get; set; }
        public string PlpickAlsoMissingMocomponent { get; set; }
        public string ConfirmStepWithPreviousQty { get; set; }
        public string ConfirmSingleMo { get; set; }
        public short? NumberOfAttempts { get; set; }
        public string DisableSubcntrOrdCheck { get; set; }
        public string DisableMaxProducibilityCheck { get; set; }
        public string DisableBoLgeneration { get; set; }
        public string DisablePickingListClosure { get; set; }
        public string DisablePickingListGeneration { get; set; }
        public string DisplayQtyZeroLots { get; set; }
        public string LotMandatoryInPl { get; set; }
        public string ScrapInvRsn { get; set; }
        public string SecondRateInvRsn { get; set; }
        public string EnableSelKanbanRtgSteps { get; set; }
        public string MultipleLots { get; set; }
        public string AllowNotPostableInPrandMo { get; set; }
        public short? MaxShiftNumber { get; set; }
        public string CancelInHouseRmreseInvRsn { get; set; }
        public string CancelOutsrcRmreseInvRsn { get; set; }
        public string ToolInvRsn { get; set; }
        public string ManufacturingLifoFifo { get; set; }
        public short? MoconfirmationsButtons { get; set; }
        public string SetProdPlanNoOnChildMo { get; set; }
        public string ExtractOnlyRtgstepMatch { get; set; }
        public string PickingFromPurch { get; set; }
        public string WmsmanufacturingLink { get; set; }
        public string WmsmanufacturingLinkOnLoad { get; set; }
        public string WmstrautomaticDevelopment { get; set; }
        public short? WmsloadingZone { get; set; }
        public string WmscheckTransferRequests { get; set; }
        public string NoVariantOnLoad { get; set; }
        public string CanEditMostepDate { get; set; }
        public string ToolIssueInvRsn { get; set; }
        public string DenyInteractToolReqPicking { get; set; }
        public string WmstrautomaticRun { get; set; }
        public string NetByMoconfirmed { get; set; }
        public string LotGenMomentItemDefault { get; set; }
        public string DnwithNetBeforePl { get; set; }
        public string GroupTo { get; set; }
        public string AllowModifyFpinMoconf { get; set; }
        public string WmstoconfPickMovedQty { get; set; }
        public string SetStatus { get; set; }
        public string RevOutsrcSrloadInvRsn { get; set; }
        public string RevOutsrcRmpickingInvRsn { get; set; }
        public string RevInHouseFpreceiptInvRsn { get; set; }
        public string RevOutsrcFpreceiptInvRsn { get; set; }
        public string RevInHouseRmissueInvRsn { get; set; }
        public string RevOutsrcRmissueInvRsn { get; set; }
        public string RevInHouseToOutsrcInvRsn { get; set; }
        public string RevOutsrcToInHouseInvRsn { get; set; }
        public string RevInHouseScrapInvRsn { get; set; }
        public string RevOutsrcScrapInvRsn { get; set; }
        public string RevOutsrcToOutsrcInvRsn { get; set; }
        public string RevInHouseSrloadInvRsn { get; set; }
        public string RevReturnedMaterialRsn { get; set; }
        public string ShowOnlyItemSupplierInPr { get; set; }
        public string Wmsrmpicking { get; set; }
        public string NoConfirmedLabour { get; set; }
        public string EditMocomponentsUnloadQty { get; set; }
        public string UnloadIepositiveAdjInvRsn { get; set; }
        public string UnloadIenegativeAdjInvRsn { get; set; }
        public string ShowLeadTimeMsg { get; set; }
        public string FurtherMoconfInSubcntrBoL { get; set; }
        public string CheckAssignedLot { get; set; }
        public string EditWaste { get; set; }
        public string UseRtgStepDate { get; set; }
        public string UseInspectionNoteStorage { get; set; }
        public string LotsAssignedByWms { get; set; }
        public string AllowEditInToconfirmimation { get; set; }
        public string UseExistingLotMo { get; set; }
        public DateTime Tbcreated { get; set; }
        public DateTime Tbmodified { get; set; }
        public int TbcreatedId { get; set; }
        public int TbmodifiedId { get; set; }
    }
}
