Module TipoServizio
    Public Function TranscodificaServizio(ByVal codice As String) As String
        Dim esito As String
        Select Case codice.ToUpper
            Case "AC"
                esito = "APECHIU"
            Case "B1"
                esito = "XXXXX"
            Case "C1"
                esito = "XXXXX"
            Case "CA"
                esito = "COLL ALLARME"
            Case "CC"
                esito = "TENUTA CHIAVI"
            Case "CO"
                esito = "COLL ALLARME"
            Case "CT"
                esito = "COLL COMBINAT"
            Case "CTKG"
                esito = "GPRS"
            Case "CV"
                esito = "CONTROLLO VISTA"
            Case "IV"
                esito = "XXXXX"
            Case "KA"
                esito = "XXXXX"
            Case "KG"
                esito = "GPRS"
            Case "KN"
                esito = "XXXXX"
            Case "KP"
                esito = "XXXXX"
            Case "L1"
                esito = "XXXXX"
            Case "MA"
                esito = "XXXXX"
            Case "NO"
                esito = ""
            Case "O1"
                esito = "XXXXX"
            Case "PA"
                esito = "XXXXX"
            Case "P1"
                esito = "PRONTO IN.TERZI"
            Case "PD"
                esito = "XXXXX"
            Case "PI"
                esito = "PRONTO INTERVEN"
            Case "PR"
                esito = "COLL RADIO"
            Case "R1"
                esito = "XXXXX"
            Case "RB"
                esito = "ISPEZIONI"
            Case "RE"
                esito = "RONDA ELE"
            Case "RO"
                esito = "BOLLATURA"
            Case "RS"
                esito = "RITIRO SCHEDE"
            Case "SN"
                esito = "SERVIZIO NEVE"
            Case "TD"
                esito = "TELEFONIA DEDIC"
            Case "TS"
                esito = "TELESOCCORSO"
            Case "VV"
                esito = "VIDEOISPEZIONI"
            Case "VX"
                esito = "SATELLITARE"
            Case "YA"
                esito = "ANTIRAPINA"

            Case Else
                esito = "XXXXX"

        End Select
        Return esito
    End Function
    Public Function TranscodificaEventoIntegra(ByVal codice As String) As String
        Dim esito As String
        Select Case codice.ToUpper
            Case "APECHIU"
                esito = "B1"
            Case "caseX"
                esito = "C1"
            Case "caseX"
                esito = "CA"
            Case "COLL ALLARME"
                esito = "CC"
            Case "TENUTA CHIAVI"
                esito = "CO"
            Case "COLL ALLARME"
                esito = "CT"
            Case "COLL COMBINAT"
                esito = "CTKG"
            Case "GPRS"
                esito = "CV"
            Case "CONTROLLO VISTA"
                esito = "IV"
            Case "caseX"
                esito = "KA"
            Case "caseX"
                esito = "KG"
            Case "GPRS"
                esito = "KN"
            Case "caseX"
                esito = "KP"
            Case "caseX"
                esito = "L1"
            Case "caseX"
                esito = "MA"
            Case "caseX"
                esito = "NO"
            Case ""
                esito = "O1"
            Case "caseX"
                esito = "PA"
            Case "caseX"
                esito = "P1"
            Case "PRONTO IN.TERZI"
                esito = "INT"
            Case "caseX"
                esito = "PI"
            Case "PRONTO INTERVEN"
                esito = "INT"
            Case "COLL RADIO"
                esito = "R1"
            Case "caseX"
                esito = "RB"
            Case "ISPEZIONI"
                esito = "ISP"
            Case "RONDA ELE"
                esito = "RO"
            Case "BOLLATURA"
                esito = "RS"
            Case "RITIRO SCHEDE"
                esito = "SN"
            Case "SERVIZIO NEVE"
                esito = "TD"
            Case "TELEFONIA DEDIC"
                esito = "TS"
            Case "TELESOCCORSO"
                esito = "VV"
            Case "VIDEOISPEZIONI"
                esito = "VX"
            Case "SATELLITARE"
                esito = "YA"
            Case "ANTIRAPINA"
                esito = "x"
            Case "INTERVENTI"
                esito = "INT"
            Case Else
                esito = "xx"
        End Select
        Return esito
    End Function
End Module
