using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace EFMago.Models
{
    public partial class MaSaleDocDetailNoRef
    {
        public int SaleDocId { get; set; }
        public short Line { get; set; }
        public int? LineType { get; set; }
        public string Description { get; set; }
        public string NoInvoice { get; set; }
        public string NoPrint { get; set; }
        public string Item { get; set; }
        public string Variant { get; set; }
        public string Drawing { get; set; }
        public string Department { get; set; }
        public string UoM { get; set; }
        public double? Qty { get; set; }
        public double? AdditionalQty1 { get; set; }
        public double? AdditionalQty2 { get; set; }
        public double? AdditionalQty3 { get; set; }
        public double? UnitValue { get; set; }
        public double? TaxableAmount { get; set; }
        public string TaxCode { get; set; }
        public double? TotalAmount { get; set; }
        public double? Discount1 { get; set; }
        public double? Discount2 { get; set; }
        public string DiscountFormula { get; set; }
        public double? DiscountAmount { get; set; }
        public string Offset { get; set; }
        public int? SaleType { get; set; }
        public short? NoOfPacks { get; set; }
        public string PacksUoM { get; set; }
        public double? GrossWeight { get; set; }
        public double? NetWeight { get; set; }
        public double? GrossVolume { get; set; }
        public string InternalIdNo { get; set; }
        public string ExternalIdNo { get; set; }
        public string IncludedInTurnover { get; set; }
        public int? DocumentType { get; set; }
        public DateTime? DocumentDate { get; set; }
        public int? CustSuppType { get; set; }
        public string CustSupp { get; set; }
        public double? AdditionalQty4 { get; set; }
        public int? SaleOrdId { get; set; }
        public string SaleOrdNo { get; set; }
        public short? SaleOrdPos { get; set; }
        public string CloseSaleOrd { get; set; }
        public int? SaleOrdSubId { get; set; }
        public short? KitNo { get; set; }
        public double? KitQty { get; set; }
        public string Lot { get; set; }
        public string Job { get; set; }
        public string CostCenter { get; set; }
        public string ProductLine { get; set; }
        public double? CommPerc { get; set; }
        public double? AreaManagerCommPerc { get; set; }
        public double? SalespersonDiscount { get; set; }
        public string CommissionCtg { get; set; }
        public double? DistributedDiscount { get; set; }
        public string Packing { get; set; }
        public int? Moid { get; set; }
        public string Mono { get; set; }
        public short? RtgStep { get; set; }
        public string Alternate { get; set; }
        public short? AltRtgStep { get; set; }
        public string Location { get; set; }
        public double? SalespersonComm { get; set; }
        public int? SubId { get; set; }
        public string IsAbom { get; set; }
        public string StoragePhase1 { get; set; }
        public string StoragePhase2 { get; set; }
        public string SpecificatorPhase1 { get; set; }
        public string SpecificatorPhase2 { get; set; }
        public short? ExternalLineReference { get; set; }
        public double? SpecWeightNetMass { get; set; }
        public double? SpecWeightNetMassSuppUnit { get; set; }
        public int? ReferenceDocId { get; set; }
        public string ReferenceDocNo { get; set; }
        public string CombinedNomenclature { get; set; }
        public string CountyOfOrigin { get; set; }
        public double? AreaManagerComm { get; set; }
        public string Notes { get; set; }
        public double? BaseSalesperson { get; set; }
        public double? BaseAreaManager { get; set; }
        public string Contribution { get; set; }
        public string AreaManagerCommCtg { get; set; }
        public string CommPercAuto { get; set; }
        public string AreaManagerCommPercAuto { get; set; }
        public string SalespersonCommAuto { get; set; }
        public string AreaManagerCommAuto { get; set; }
        public string SalespersonCommCtgAuto { get; set; }
        public string AreaManagerCommCtgAuto { get; set; }
        public string FixedCost { get; set; }
        public int? InvoiceId { get; set; }
        public int? InvoiceSubId { get; set; }
        public string CorrectionDocChargeLine { get; set; }
        public string CorrectedDocumentLine { get; set; }
        public int? ReturnFromCustomerId { get; set; }
        public int? ReturnFromCustomerSubId { get; set; }
        public double? ReturnFromCustomerQty { get; set; }
        public int? ReferenceDocumentId { get; set; }
        public int? ReferenceDocSubId { get; set; }
        public short? ReferenceDocLine { get; set; }
        public string ReturnReason { get; set; }
        public int? DocIdToBeUnloaded { get; set; }
        public short? DocRowToBeUnloaded { get; set; }
        public DateTime? DepartureDate { get; set; }
        public double? CorrectionQty { get; set; }
        public double? OriginalQty { get; set; }
        public double? OriginalUnitValue { get; set; }
        public double? PurchaseUnitValue { get; set; }
        public string CorrectionDocument { get; set; }
        public double? InvoicedQty { get; set; }
        public string Invoiced { get; set; }
        public string InvoiceForAdvanceLinked { get; set; }
        public double? InvoiceAmount { get; set; }
        public int? InvoiceForAdvanceId { get; set; }
        public int? InvoiceForAdvanceSubId { get; set; }
        public int? ProFormaInvoiceId { get; set; }
        public int? ProFormaInvoiceSubId { get; set; }
        public string CancelledInCd { get; set; }
        public string NotPostableInInventory { get; set; }
        public string SubjectToWithholdingTax { get; set; }
        public double? LineCost { get; set; }
        public string PriceList { get; set; }
        public string Delivered { get; set; }
        public double? DeliveredQty { get; set; }
        public int? ReferenceDocType { get; set; }
        public string Cpacode { get; set; }
        public string ServiceToIncludeInIntrastat { get; set; }
        public int? IntrastatSupplyType { get; set; }
        public double? QtyLoadedInCn { get; set; }
        public string LoadedInCn { get; set; }
        public int? CrrefType { get; set; }
        public int? CrrefId { get; set; }
        public int? CrrefSubId { get; set; }
        public short? CrrefLine { get; set; }
        public double? ActualRetailPrice { get; set; }
        public string ActualRetailPriceWithTax { get; set; }
        public double? ActualRetailPricePhase2 { get; set; }
        public int? PerishablesType { get; set; }
        public double? DistributedShipCharges { get; set; }
        public double? DistributedAdvanceAmount { get; set; }
        public double? DistributedAdvanceAmount2 { get; set; }
        public double? DistributedAdvanceAmount3 { get; set; }
        public double? DistributedAllowances { get; set; }
        public double? DistributedAdditionalCharges { get; set; }
        public double? DistributedInsuranceCharges { get; set; }
        public string DistributeCharges { get; set; }
        public string TaxRuleCode { get; set; }
        public string TaxRuleCodeCompany { get; set; }
        public string ExcludeIcmsst { get; set; }
        public string ExcludeFromTot { get; set; }
        public double? NetPrice { get; set; }
        public string NetPriceIsAuto { get; set; }
        public int? Trid { get; set; }
        public string AuthorCode { get; set; }
        public DateTime Tbcreated { get; set; }
        public DateTime Tbmodified { get; set; }
        public int TbcreatedId { get; set; }
        public int TbmodifiedId { get; set; }
        public string ImStorage { get; set; }
        public string ImJobGroup { get; set; }
        public int? ImDeliveryRequestId { get; set; }
        public short? ImDelReqLine { get; set; }
        public string ImJobWorkingStep { get; set; }
        public string InEi { get; set; }
        public double? AllNrCanoni { get; set; }
        public DateTime? AllCanoniDataI { get; set; }
        public DateTime? AllCanoniDataF { get; set; }

        public virtual MaSaleDocNoRef SaleDocNavigation { get; set; }
    }
}
